.TH "src Directory Reference" 3 "Fri Apr 22 2016" "ChipChipArray" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAdafruit_PWMServoDriver\&.cpp\fP"
.br
.RI "\fIContains the function and class definitions necessary for the PWM servo driver\&. \fP"
.ti -1c
.RI "file \fBAdafruit_PWMServoDriver\&.h\fP"
.br
.ti -1c
.RI "file \fBArm\&.hpp\fP"
.br
.RI "\fIContains the Arm class used to control the robotic arm\&. \fP"
.ti -1c
.RI "file \fBBlock\&.hpp\fP"
.br
.RI "\fIContains Block class\&. \fP"
.ti -1c
.RI "file \fBcv_hue\&.cpp\fP"
.br
.RI "\fIContains program formally used to find HSV values for blocks\&. \fP"
.ti -1c
.RI "file \fBcv_shape\&.cpp\fP"
.br
.RI "\fIContains a program to aid in determining HSV ranges\&. \fP"
.ti -1c
.RI "file \fBcv_test\&.cpp\fP"
.br
.RI "\fIContains program used to test PiCamera class\&. \fP"
.ti -1c
.RI "file \fBdark_magic\&.cpp\fP"
.br
.RI "\fIContains test code for arm\&. \fP"
.ti -1c
.RI "file \fBdefinitions\&.hpp\fP"
.br
.RI "\fIContains definitions for architecture-independant numeric variables, enumerations and enumerated classes, and #define'd constants, and to_sting() overloads for the enumerated classes\&. \fP"
.ti -1c
.RI "file \fBGrabber\&.hpp\fP"
.br
.RI "\fIContains the Grabber class\&. \fP"
.ti -1c
.RI "file \fBimg\&.cpp\fP"
.br
.RI "\fIContains a program to display the current camera image\&. \fP"
.ti -1c
.RI "file \fBjacob_alg_test\&.cpp\fP"
.br
.RI "\fIContains a program that tests Jacob's yellow-detection algorithm\&. \fP"
.ti -1c
.RI "file \fBloading_test\&.cpp\fP"
.br
.RI "\fIContains a program to test Grabber class\&. \fP"
.ti -1c
.RI "file \fBLog\&.hpp\fP"
.br
.RI "\fIContains Log class\&. \fP"
.ti -1c
.RI "file \fBlog_test\&.cpp\fP"
.br
.RI "\fIContains a program to test partially the Log class\&. \fP"
.ti -1c
.RI "file \fBmain\&.cpp\fP"
.br
.RI "\fIContains the \fBmain()\fP function to the whole project\&. \fP"
.ti -1c
.RI "file \fBNavigationControl\&.cpp\fP"
.br
.RI "\fIContains the navigation control function definitions\&. \fP"
.ti -1c
.RI "file \fBNavigationControl\&.h\fP"
.br
.RI "\fIContains the function definitions for navigation control\&. \fP"
.ti -1c
.RI "file \fBnet_qr_test\&.cpp\fP"
.br
.RI "\fIContains test program for reading QR codes\&. \fP"
.ti -1c
.RI "file \fBold_cv_test\&.cpp\fP"
.br
.RI "\fIContains old test program for the RaspiCam_Cv class\&. \fP"
.ti -1c
.RI "file \fBPiCamera\&.hpp\fP"
.br
.RI "\fIContains PiCamera class\&. \fP"
.ti -1c
.RI "file \fBqr_test\&.cpp\fP"
.br
.RI "\fIContains test program for \fBScanQR()\fP function\&. \fP"
.ti -1c
.RI "file \fBScanQR\&.hpp\fP"
.br
.RI "\fIContains \fBScanQR()\fP function\&. \fP"
.ti -1c
.RI "file \fBServo_Position_Shell\&.cpp\fP"
.br
.RI "\fICOntains the function definitions for the servo position shell\&. \fP"
.ti -1c
.RI "file \fBServo_Position_Shell\&.h\fP"
.br
.RI "\fIContains the function prototypes for the servo position shell\&. \fP"
.in -1c
