.TH "src/Adafruit_PWMServoDriver.cpp" 3 "Fri Apr 22 2016" "ChipChipArray" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Adafruit_PWMServoDriver.cpp \- 
.PP
Contains the function and class definitions necessary for the PWM servo driver\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'Adafruit_PWMServoDriver\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBENABLE_DEBUG_OUTPUT\fP   false"
.br
.in -1c
.SH "Detailed Description"
.PP 
Contains the function and class definitions necessary for the PWM servo driver\&. 


.PP
\fBAuthor:\fP
.RS 4
Limor Frief/Ladyadda 
.PP
Nickolas Neely 
.RE
.PP

.PP
Definition in file \fBAdafruit_PWMServoDriver\&.cpp\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define ENABLE_DEBUG_OUTPUT   false"

.PP
Definition at line 35 of file Adafruit_PWMServoDriver\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ChipChipArray from the source code\&.
