.TH "Adafruit_PWMServoDriver" 3 "Tue Mar 8 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Adafruit_PWMServoDriver \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Adafruit_PWMServoDriver\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAdafruit_PWMServoDriver\fP (\fBuint8_t\fP addr=0x41)"
.br
.ti -1c
.RI "void \fBbegin\fP (void)"
.br
.ti -1c
.RI "void \fBreset\fP (void)"
.br
.ti -1c
.RI "void \fBsetPWMFreq\fP (float freq)"
.br
.ti -1c
.RI "void \fBsetPWM\fP (\fBuint8_t\fP num, \fBuint16_t\fP on, \fBuint16_t\fP off)"
.br
.ti -1c
.RI "void \fBsetPin\fP (\fBuint8_t\fP num, \fBuint16_t\fP val, bool invert=false)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 65 of file Adafruit_PWMServoDriver\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Adafruit_PWMServoDriver::Adafruit_PWMServoDriver (\fBuint8_t\fPaddr = \fC0x41\fP)"

.PP
Definition at line 29 of file Adafruit_PWMServoDriver\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void Adafruit_PWMServoDriver::begin (void)"

.PP
Definition at line 34 of file Adafruit_PWMServoDriver\&.cpp\&.
.SS "void Adafruit_PWMServoDriver::reset (void)"

.PP
Definition at line 42 of file Adafruit_PWMServoDriver\&.cpp\&.
.SS "void Adafruit_PWMServoDriver::setPin (\fBuint8_t\fPnum, \fBuint16_t\fPval, boolinvert = \fCfalse\fP)"

.PP
Definition at line 108 of file Adafruit_PWMServoDriver\&.cpp\&.
.SS "void Adafruit_PWMServoDriver::setPWM (\fBuint8_t\fPnum, \fBuint16_t\fPon, \fBuint16_t\fPoff)"

.PP
Definition at line 73 of file Adafruit_PWMServoDriver\&.cpp\&.
.SS "void Adafruit_PWMServoDriver::setPWMFreq (floatfreq)"

.PP
Definition at line 46 of file Adafruit_PWMServoDriver\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
