.TH "src/Adafruit_PWMServoDriver.h" 3 "Fri Apr 22 2016" "ChipChipArray" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Adafruit_PWMServoDriver.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <wiringPi\&.h>\fP
.br
\fC#include <ctype\&.h>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <wiringPiI2C\&.h>\fP
.br
\fC#include <cmath>\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAdafruit_PWMServoDriver\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPCA9685_SUBADR1\fP   0x2"
.br
.ti -1c
.RI "#define \fBPCA9685_SUBADR2\fP   0x3"
.br
.ti -1c
.RI "#define \fBPCA9685_SUBADR3\fP   0x4"
.br
.ti -1c
.RI "#define \fBPCA9685_MODE1\fP   0x0"
.br
.ti -1c
.RI "#define \fBPCA9685_PRESCALE\fP   0xFE"
.br
.ti -1c
.RI "#define \fBLED0_ON_L\fP   0x6"
.br
.ti -1c
.RI "#define \fBLED0_ON_H\fP   0x7"
.br
.ti -1c
.RI "#define \fBLED0_OFF_L\fP   0x8"
.br
.ti -1c
.RI "#define \fBLED0_OFF_H\fP   0x9"
.br
.ti -1c
.RI "#define \fBALLLED_ON_L\fP   0xFA"
.br
.ti -1c
.RI "#define \fBALLLED_ON_H\fP   0xFB"
.br
.ti -1c
.RI "#define \fBALLLED_OFF_L\fP   0xFC"
.br
.ti -1c
.RI "#define \fBALLLED_OFF_H\fP   0xFD"
.br
.ti -1c
.RI "#define \fBuint8_t\fP   unsigned char"
.br
.ti -1c
.RI "#define \fBuint16_t\fP   unsigned short int"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Limor Fried/Ladyada 
.PP
Nickolas Neely  Contains the function and class headers necessary for the PWM servo driver\&. 
.RE
.PP

.PP
Definition in file \fBAdafruit_PWMServoDriver\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define ALLLED_OFF_H   0xFD"

.PP
Definition at line 62 of file Adafruit_PWMServoDriver\&.h\&.
.SS "#define ALLLED_OFF_L   0xFC"

.PP
Definition at line 61 of file Adafruit_PWMServoDriver\&.h\&.
.SS "#define ALLLED_ON_H   0xFB"

.PP
Definition at line 60 of file Adafruit_PWMServoDriver\&.h\&.
.SS "#define ALLLED_ON_L   0xFA"

.PP
Definition at line 59 of file Adafruit_PWMServoDriver\&.h\&.
.SS "#define LED0_OFF_H   0x9"

.PP
Definition at line 57 of file Adafruit_PWMServoDriver\&.h\&.
.SS "#define LED0_OFF_L   0x8"

.PP
Definition at line 56 of file Adafruit_PWMServoDriver\&.h\&.
.SS "#define LED0_ON_H   0x7"

.PP
Definition at line 55 of file Adafruit_PWMServoDriver\&.h\&.
.SS "#define LED0_ON_L   0x6"

.PP
Definition at line 54 of file Adafruit_PWMServoDriver\&.h\&.
.SS "#define PCA9685_MODE1   0x0"

.PP
Definition at line 51 of file Adafruit_PWMServoDriver\&.h\&.
.SS "#define PCA9685_PRESCALE   0xFE"

.PP
Definition at line 52 of file Adafruit_PWMServoDriver\&.h\&.
.SS "#define PCA9685_SUBADR1   0x2"

.PP
Definition at line 47 of file Adafruit_PWMServoDriver\&.h\&.
.SS "#define PCA9685_SUBADR2   0x3"

.PP
Definition at line 48 of file Adafruit_PWMServoDriver\&.h\&.
.SS "#define PCA9685_SUBADR3   0x4"

.PP
Definition at line 49 of file Adafruit_PWMServoDriver\&.h\&.
.SS "#define uint16_t   unsigned short int"

.PP
Definition at line 69 of file Adafruit_PWMServoDriver\&.h\&.
.SS "#define uint8_t   unsigned char"

.PP
Definition at line 65 of file Adafruit_PWMServoDriver\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ChipChipArray from the source code\&.
