.TH "src/Arm.hpp" 3 "Fri Apr 22 2016" "The Automatic Vasospasm Detection Application" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Arm.hpp \- 
.PP
Contains the Arm class used to control the robotic arm\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <unistd\&.h>\fP
.br
\fC#include 'definitions\&.hpp'\fP
.br
\fC#include 'Servo_Position_Shell\&.cpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBChipChipArray::Arm\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBChipChipArray\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBWRIST_TWIST\fP   \fBWRIST_PAN\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Contains the Arm class used to control the robotic arm\&. 


.PP
\fBAuthor:\fP
.RS 4
Samuel Andrew Wisner, awisner94@gmail.com 
.RE
.PP

.PP
Definition in file \fBArm\&.hpp\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define WRIST_TWIST   \fBWRIST_PAN\fP"

.PP
Definition at line 15 of file Arm\&.hpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for The Automatic Vasospasm Detection Application from the source code\&.
