.TH "src/Block.hpp" 3 "Fri Apr 22 2016" "The Automatic Vasospasm Detection Application" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Block.hpp \- 
.PP
Contains Block class\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <opencv2/core/core\&.hpp>\fP
.br
\fC#include 'definitions\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBChipChipArray::Block\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBChipChipArray\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Contains Block class\&. 


.PP
\fBAuthor:\fP
.RS 4
Samuel Andrew Wisner, awisner94@gmail.com 
.RE
.PP

.PP
Definition in file \fBBlock\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for The Automatic Vasospasm Detection Application from the source code\&.
