.TH "ChipChipArray::Log" 3 "Tue Mar 8 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ChipChipArray::Log \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Log\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLog\fP ()"
.br
.ti -1c
.RI "\fBLog\fP (auto dir, \fBLogMode\fP mode=\fBLogMode::Text\fP)"
.br
.ti -1c
.RI "\fB~Log\fP ()"
.br
.ti -1c
.RI "void \fBDebug\fP (auto mesg)"
.br
.ti -1c
.RI "void \fBError\fP (auto mesg)"
.br
.ti -1c
.RI "void \fBImage\fP (cv::Mat image, auto filename)"
.br
.ti -1c
.RI "void \fBOpen\fP (auto dir, \fBLogMode\fP mode=\fBLogMode::Text\fP)"
.br
.ti -1c
.RI "void \fBStatus\fP (auto mesg)"
.br
.ti -1c
.RI "void \fBVariable\fP (auto name, auto value)"
.br
.ti -1c
.RI "void \fBVerbose\fP (auto mesg)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class logs the text and images passed to it to specificed directory\&.
.PP
A 'container' directory to which the class can write is passed in the constructor\&. When the \fBLog\fP is initialized with \fBLogMode::Text\fP, a new log file is created with a filename based on the time of initialization in the given directory\&. When initialized in \fBLogMode::Multi\fP, it will create a subdirectory in the given directory with a name based on time\&. In this new directory, a log file will be created\&. Images may later be stored in this directory with names based on the order in which they were saved\&.
.PP
This class DOES NOT WORK without compiling without a 'LOG' definition (#define LOG or -DLOG)\&. 
.PP
Definition at line 34 of file Log\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ChipChipArray::Log::Log ()\fC [inline]\fP"
Initializes \fBLog\fP object but does not open log\&. \fBOpen()\fP must be called\&. 
.PP
Definition at line 40 of file Log\&.hpp\&.
.SS "ChipChipArray::Log::Log (autodir, \fBLogMode\fPmode = \fC\fBLogMode::Text\fP\fP)"
Initializes the \fBLog\fP\&.
.PP
A new log file is created in dir if \fBLogMode::Text\fP is given\&. The file will have a name based on the current date and time\&. If \fBLogMode::Multi\fP is given, a new directory is created, and a log file with a name based on the current date and time is created inside it\&.
.PP
\fBParameters:\fP
.RS 4
\fIdir\fP the directory for the newly created logfile/folder
.br
\fImode\fP the LogMode 
.RE
.PP

.PP
Definition at line 186 of file Log\&.hpp\&.
.SS "ChipChipArray::Log::~Log ()"
Destroys the \fBLog\fP and closes the logfile\&. 
.PP
Definition at line 192 of file Log\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void ChipChipArray::Log::Debug (automesg)"
Writes 'DEBUG: ' to the log file along with the message passed\&. Should be used for generic debugging information\&. If recording the value of a variable in the \fBLog\fP is desired, use the function \fBVariable()\fP instead\&.
.PP
\fBParameters:\fP
.RS 4
\fImesg\fP the message to record in the logfile 
.RE
.PP

.PP
Definition at line 204 of file Log\&.hpp\&.
.SS "void ChipChipArray::Log::Error (automesg)"
Writes 'ERROR: ' to the log file\&. Should only be use when an exception is thrown\&.
.PP
\fBParameters:\fP
.RS 4
\fImesg\fP the message to record in the log 
.RE
.PP

.PP
Definition at line 215 of file Log\&.hpp\&.
.SS "void ChipChipArray::Log::Image (cv::Matimage, autofilename)"
Creates a bitmap image in the subdirectory created by the \fBLog\fP during initialization\&. Does nothing if \fBLogMode::Text\fP was passed in the constructor\&.
.PP
\fBParameters:\fP
.RS 4
\fIimage\fP the image to save 
.br
\fIfilename\fP the filename for the saved image 
.RE
.PP

.PP
Definition at line 226 of file Log\&.hpp\&.
.SS "void ChipChipArray::Log::Open (autodir, \fBLogMode\fPmode = \fC\fBLogMode::Text\fP\fP)"

.PP
Definition at line 246 of file Log\&.hpp\&.
.SS "void ChipChipArray::Log::Status (automesg)"
Writes 'STATUS: ' to the log file\&. Should be used when recording the status or state of the program\&. It should not be used to record microalgorithmic changes\&. Use \fBVerbose()\fP for these instead\&.
.PP
\fBParameters:\fP
.RS 4
\fImesg\fP the message to record in the logfile 
.RE
.PP

.PP
Definition at line 289 of file Log\&.hpp\&.
.SS "void ChipChipArray::Log::Variable (autoname, autovalue)"
Writes 'VARIABLE: ' to the log file\&. Should be used whenever recording the value of a variable is desired\&.
.PP
\fBParameters:\fP
.RS 4
\fIname\fP the variable name to record 
.br
\fIvalue\fP the variable value to record 
.RE
.PP

.PP
Definition at line 300 of file Log\&.hpp\&.
.SS "void ChipChipArray::Log::Verbose (automesg)"
Writes 'VERBOSE: ' to the log file\&. Should only be used for recording small, specific portions of code\&. To record a change in the more general state of the program, use \fBStatus()\fP instead\&.
.PP
\fBParameters:\fP
.RS 4
\fImesg\fP the message to record in the logfile 
.RE
.PP

.PP
Definition at line 312 of file Log\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
