.TH "ChipChipArray" 3 "Sat Mar 5 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ChipChipArray \- 
.PP
contains \fBBlock\fP class  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBArm\fP"
.br
.ti -1c
.RI "class \fBBlock\fP"
.br
.ti -1c
.RI "class \fBLog\fP"
.br
.ti -1c
.RI "class \fBPiCamera\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.ti -1c
.RI "\fBColor\fP \fBScanQR\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBuint8\fP \fBqrInvokeCount\fP = 0"
.br
.ti -1c
.RI "\fBLog\fP \fBscanQrLog\fP ('logs/\fBScanQR\fP', LogMode::Multi)"
.br
.in -1c
.SH "Detailed Description"
.PP 
contains \fBBlock\fP class 

contains \fBScanQR()\fP function
.PP
contains \fBPiCamera\fP class
.PP
contains \fBLog\fP class
.PP
\fBAuthor:\fP
.RS 4
Samuel Andrew Wisner, awisner94@gmail.com 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "int ChipChipArray::main (intargc, char **argv)"
This program was used before \fBcv_shape\&.cpp\fP was written to find HSV ranges for the different color blocks\&. This is a slightly modified version of some code written by Shermal Fernando in the blog post 'Color Detection & Object Tracking' at http://opencv-srf.blogspot.com/2010/09/object-detection-using-color-seperation.html"\&. 
.PP
Definition at line 26 of file cv_hue\&.cpp\&.
.SS "\fBColor\fP ChipChipArray::ScanQR ()"
This function manuvers arm to look at the QR code on a train car as the robot is backing up to the car\&. It attempts to find the code in multiple images before finally throwing an exeption if a code is not found\&. If multiple codes are found, it returns a single Color by (seemingly) arbitrary decision\&.
.PP
This function is based on code written by Michael Young (https://github.com/ayoungprogrammer/WebcamCodeScanner)\&. 
.PP
Definition at line 33 of file ScanQR\&.hpp\&.
.SH "Variable Documentation"
.PP 
.SS "\fBuint8\fP ChipChipArray::qrInvokeCount = 0"

.PP
Definition at line 20 of file ScanQR\&.hpp\&.
.SS "\fBLog\fP ChipChipArray::scanQrLog('logs/\fBScanQR\fP', LogMode::Multi)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
