.TH "ChipChipArray::PiCamera" 3 "Tue Mar 8 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ChipChipArray::PiCamera \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PiCamera\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPiCamera\fP ()"
.br
.ti -1c
.RI "\fBPiCamera\fP (bool useColor)"
.br
.ti -1c
.RI "void \fBClose\fP ()"
.br
.ti -1c
.RI "cv::Mat \fBSnap\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class is a basic wrapper to allow the Raspicam to interface with OpenCV\&. It uses another wrapper class, Raspicam, provided by Cédric Verstraeten (https://github.com/cedricve/raspicam)\&. 
.PP
Definition at line 23 of file PiCamera\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ChipChipArray::PiCamera::PiCamera ()\fC [inline]\fP"
Opens the camera and configures it for color images\&. 
.PP
Definition at line 28 of file PiCamera\&.hpp\&.
.SS "ChipChipArray::PiCamera::PiCamera (booluseColor)"
Opens the camera\&.
.PP
\fBParameters:\fP
.RS 4
\fIuseColor\fP Specifices whether camera should make color images\&. TRUE = color, FALSE = grayscale\&. 
.RE
.PP

.PP
Definition at line 58 of file PiCamera\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void ChipChipArray::PiCamera::Close ()"
Closes connection to camera\&. 
.PP
Definition at line 64 of file PiCamera\&.hpp\&.
.SS "cv::Mat ChipChipArray::PiCamera::Snap ()"
Makes picture\&.
.PP
\fBReturns:\fP
.RS 4
OpenCV Mat object (i\&.e\&., an image) from the camera 
.RE
.PP

.PP
Definition at line 68 of file PiCamera\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
