.TH "src/cv_hue.cpp" 3 "Fri Apr 22 2016" "The Automatic Vasospasm Detection Application" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/cv_hue.cpp \- 
.PP
Contains program formally used to find HSV values for blocks\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include 'opencv2/highgui/highgui\&.hpp'\fP
.br
\fC#include 'opencv2/imgproc/imgproc\&.hpp'\fP
.br
\fC#include 'PiCamera\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBChipChipArray\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBChipChipArray::main\fP (int argc, char **argv)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Contains program formally used to find HSV values for blocks\&. 


.PP
\fBAuthor:\fP
.RS 4
Shermal Fernando 
.PP
Samuel Andrew Wisner, awisner94@gmail.com 
.RE
.PP

.PP
Definition in file \fBcv_hue\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for The Automatic Vasospasm Detection Application from the source code\&.
