.TH "src/cv_hue.cpp" 3 "Tue Mar 8 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/cv_hue.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include 'opencv2/highgui/highgui\&.hpp'\fP
.br
\fC#include 'opencv2/imgproc/imgproc\&.hpp'\fP
.br
\fC#include 'PiCamera\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBChipChipArray\fP"
.br
.RI "\fIcontains \fBBlock\fP class \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBChipChipArray::main\fP (int argc, char **argv)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
