.TH "src/cv_shape.cpp" 3 "Sun Feb 28 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/cv_shape.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <opencv2/highgui/highgui\&.hpp>\fP
.br
\fC#include <opencv2/imgproc/imgproc\&.hpp>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'definitions\&.hpp'\fP
.br
\fC#include 'PiCamera\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"
This program (a single function) is a test of the computer vision algorithms for loading the blocks\&. It will likely be in development for some time to come\&. The plan currently is to develop and test all CV algorithms for block loading here before moving it all into class functions and testing again\&.
.PP
This code is based on several online articles:
.IP "\(bu" 2
'Color Detectionn & Object Tracking' by Shermal Fernando (http://opencv-srf.blogspot.com/2010/09/object-detection-using-color-seperation.html)
.IP "\(bu" 2
'Shape Detection & Tracking using Contours' by Shermal Fernando (http://opencv-srf.blogspot.com/2011/09/object-detection-tracking-using-contours.html)
.IP "\(bu" 2
'Creating Bounding boxes and circles for contours' in the OpenCV 2\&.4 Tutorials (http://opencv-srf.blogspot.com/2011/09/object-detection-tracking-using-contours.html) 
.PP

.PP
Definition at line 30 of file cv_shape\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
