.TH "src/cv_test.cpp" 3 "Sun Feb 28 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/cv_test.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include 'definitions\&.hpp'\fP
.br
\fC#include 'Block\&.hpp'\fP
.br
\fC#include 'Grabber\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"
This program was used solely to test the PiCamera wrapper class and its compatibility with the raspicam wrapper and ultimately OpenCV\&. 
.PP
Definition at line 13 of file cv_test\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
