.TH "src/definitions.hpp" 3 "Tue Mar 8 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/definitions.hpp \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBstd\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBENUM\fP   signed char"
.br
.RI "\fIcontains definitions for architecture-independant numeric variables, enumerations and enumerated classes, and #define'd constants, and to_sting() overloads for the enumerated classes\&. \fP"
.ti -1c
.RI "#define \fBERROR\fP   -1"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef unsigned char \fBbyte\fP"
.br
.ti -1c
.RI "typedef unsigned char \fBuint8\fP"
.br
.ti -1c
.RI "typedef signed char \fBsint8\fP"
.br
.ti -1c
.RI "typedef unsigned short \fBuint16\fP"
.br
.ti -1c
.RI "typedef signed short \fBsint16\fP"
.br
.ti -1c
.RI "typedef unsigned int \fBuint32\fP"
.br
.ti -1c
.RI "typedef signed int \fBsint32\fP"
.br
.ti -1c
.RI "typedef unsigned long long \fBuint64\fP"
.br
.ti -1c
.RI "typedef signed long long \fBsint64\fP"
.br
.ti -1c
.RI "typedef float \fBfloat32\fP"
.br
.ti -1c
.RI "typedef double \fBfloat64\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBBlockPosition\fP : ENUM { \fBBlockPosition::Front\fP, \fBBlockPosition::Back\fP }"
.br
.ti -1c
.RI "enum \fBColor\fP : ENUM { \fBColor::Red\fP, \fBColor::Yellow\fP, \fBColor::Green\fP, \fBColor::Blue\fP, \fBColor::Perrywinkle\fP }"
.br
.ti -1c
.RI "enum \fBLogMode\fP : ENUM { \fBLogMode::Text\fP, \fBLogMode::Multi\fP }"
.br
.ti -1c
.RI "enum \fBResult\fP : ENUM { \fBResult::No_Blocks\fP = -1, \fBResult::No_Halves\fP = 0, \fBResult::Two_Halves\fP = 2, \fBResult::Four_Halves\fP = 4 }"
.br
.ti -1c
.RI "enum \fBSide\fP : ENUM { \fBSide::Left\fP, \fBSide::Right\fP }"
.br
.ti -1c
.RI "enum \fBSize\fP : ENUM { \fBSize::Short\fP, \fBSize::Long\fP }"
.br
.ti -1c
.RI "enum \fBZone\fP : ENUM { \fBZone::A\fP = 'A', \fBZone::B\fP = 'B', \fBZone::C\fP = 'C' }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "string \fBstd::to_string\fP (\fBBlockPosition\fP pos)"
.br
.ti -1c
.RI "string \fBstd::to_string\fP (\fBColor\fP color)"
.br
.ti -1c
.RI "string \fBstd::to_string\fP (\fBLogMode\fP mode)"
.br
.ti -1c
.RI "string \fBstd::to_string\fP (\fBResult\fP res)"
.br
.ti -1c
.RI "string \fBstd::to_string\fP (\fBSide\fP side)"
.br
.ti -1c
.RI "string \fBstd::to_string\fP (\fBSize\fP size)"
.br
.ti -1c
.RI "string \fBstd::to_string\fP (\fBZone\fP zone)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ENUM   signed char"

.PP
contains definitions for architecture-independant numeric variables, enumerations and enumerated classes, and #define'd constants, and to_sting() overloads for the enumerated classes\&. 
.PP
\fBAuthor:\fP
.RS 4
Samuel Andrew Wisner, awisner94@gmail.com 
.RE
.PP

.PP
Definition at line 11 of file definitions\&.hpp\&.
.SS "#define ERROR   -1"

.PP
Definition at line 12 of file definitions\&.hpp\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef unsigned char \fBbyte\fP"

.PP
Definition at line 14 of file definitions\&.hpp\&.
.SS "typedef float \fBfloat32\fP"

.PP
Definition at line 27 of file definitions\&.hpp\&.
.SS "typedef double \fBfloat64\fP"

.PP
Definition at line 28 of file definitions\&.hpp\&.
.SS "typedef signed short \fBsint16\fP"

.PP
Definition at line 19 of file definitions\&.hpp\&.
.SS "typedef signed int \fBsint32\fP"

.PP
Definition at line 22 of file definitions\&.hpp\&.
.SS "typedef signed long long \fBsint64\fP"

.PP
Definition at line 25 of file definitions\&.hpp\&.
.SS "typedef signed char \fBsint8\fP"

.PP
Definition at line 16 of file definitions\&.hpp\&.
.SS "typedef unsigned short \fBuint16\fP"

.PP
Definition at line 18 of file definitions\&.hpp\&.
.SS "typedef unsigned int \fBuint32\fP"

.PP
Definition at line 21 of file definitions\&.hpp\&.
.SS "typedef unsigned long long \fBuint64\fP"

.PP
Definition at line 24 of file definitions\&.hpp\&.
.SS "typedef unsigned char \fBuint8\fP"

.PP
Definition at line 15 of file definitions\&.hpp\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBBlockPosition\fP : \fBENUM\fP\fC [strong]\fP"
The position of the block relative to the arm\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIFront \fP\fP
.TP
\fB\fIBack \fP\fP
.PP
Definition at line 31 of file definitions\&.hpp\&.
.SS "enum \fBColor\fP : \fBENUM\fP\fC [strong]\fP"
The color of a block or train car\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIRed \fP\fP
.TP
\fB\fIYellow \fP\fP
.TP
\fB\fIGreen \fP\fP
.TP
\fB\fIBlue \fP\fP
.TP
\fB\fIPerrywinkle \fP\fP
.PP
Definition at line 37 of file definitions\&.hpp\&.
.SS "enum \fBLogMode\fP : \fBENUM\fP\fC [strong]\fP"
The mode in which the Log should prepare (i\&.e\&., text only or text and images)\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIText \fP\fP
.TP
\fB\fIMulti \fP\fP
.PP
Definition at line 49 of file definitions\&.hpp\&.
.SS "enum \fBResult\fP : \fBENUM\fP\fC [strong]\fP"
The number of half blocks picked up in a stack\&. The integer value of the 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fINo_Blocks \fP\fP
.TP
\fB\fINo_Halves \fP\fP
.TP
\fB\fITwo_Halves \fP\fP
.TP
\fB\fIFour_Halves \fP\fP
.PP
Definition at line 58 of file definitions\&.hpp\&.
.SS "enum \fBSide\fP : \fBENUM\fP\fC [strong]\fP"
Represents which block to pick up when multiple blocks are visible\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fILeft \fP\fP
.TP
\fB\fIRight \fP\fP
.PP
Definition at line 66 of file definitions\&.hpp\&.
.SS "enum \fBSize\fP : \fBENUM\fP\fC [strong]\fP"
The block size, either 2\&.5' or 5'\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIShort \fP\fP
.TP
\fB\fILong \fP\fP
.PP
Definition at line 72 of file definitions\&.hpp\&.
.SS "enum \fBZone\fP : \fBENUM\fP\fC [strong]\fP"
Zone A, B, or C 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIA \fP\fP
.TP
\fB\fIB \fP\fP
.TP
\fB\fIC \fP\fP
.PP
Definition at line 78 of file definitions\&.hpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
