.TH "src/Grabber.hpp" 3 "Fri Apr 22 2016" "ChipChipArray" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Grabber.hpp \- 
.PP
Contains the Grabber class\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <cmath>\fP
.br
\fC#include <map>\fP
.br
\fC#include <opencv2/highgui/highgui\&.hpp>\fP
.br
\fC#include <opencv2/imgproc/imgproc\&.hpp>\fP
.br
\fC#include <string>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'Arm\&.hpp'\fP
.br
\fC#include 'definitions\&.hpp'\fP
.br
\fC#include 'Block\&.hpp'\fP
.br
\fC#include 'Log\&.hpp'\fP
.br
\fC#include 'PiCamera\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBChipChipArray::Grabber\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBChipChipArray\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Contains the Grabber class\&. 


.PP
\fBAuthor:\fP
.RS 4
Samuel Andrew Wisner, awisner94@gmail.com 
.RE
.PP

.PP
Definition in file \fBGrabber\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ChipChipArray from the source code\&.
