.TH "src/jacob_alg_test.cpp" 3 "Tue Mar 8 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/jacob_alg_test.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <opencv2/core/core\&.hpp>\fP
.br
\fC#include <opencv2/imgproc/imgproc\&.hpp>\fP
.br
\fC#include 'PiCamera\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"
This program tests Jacob Laurel's algorithm for detecting yellow blocks (RGB=>YUV, HSV=>RGB)\&. 
.PP
Definition at line 20 of file jacob_alg_test\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
