.TH "src/loading_test.cpp" 3 "Sat Mar 5 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/loading_test.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include 'definitions\&.hpp'\fP
.br
\fC#include 'Block\&.hpp'\fP
.br
\fC#include 'Grabber\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"
This program was used solely to test the Grabber class\&. It moves the arm and picks up blocks\&. 
.PP
Definition at line 18 of file loading_test\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
