.TH "src/loading_test.cpp" 3 "Fri Apr 22 2016" "ChipChipArray" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/loading_test.cpp \- 
.PP
Contains a program to test Grabber class\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include 'definitions\&.hpp'\fP
.br
\fC#include 'Block\&.hpp'\fP
.br
\fC#include 'Grabber\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Contains a program to test Grabber class\&. 


.PP
\fBAuthor:\fP
.RS 4
Samuel Andrew Wisner, awisner94@gmail.com 
.RE
.PP

.PP
Definition in file \fBloading_test\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main ()"
This program was used solely to test the Grabber class\&. It moves the arm and picks up blocks\&. 
.PP
Definition at line 19 of file loading_test\&.cpp\&.
.PP
.nf
19            {
20     setup();
21     Grabber g(Zone::A, Side::Left);
22     g\&.Load();
23     g\&.Close();
24 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for ChipChipArray from the source code\&.
