.TH "src/log_test.cpp" 3 "Sat Mar 5 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/log_test.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'definitions\&.hpp'\fP
.br
\fC#include 'Log\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"
This program partially tests the Log class\&. 
.PP
Definition at line 17 of file log_test\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
