.TH "src/log_test.cpp" 3 "Fri Apr 22 2016" "ChipChipArray" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/log_test.cpp \- 
.PP
contains a program to test partially the Log class  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'definitions\&.hpp'\fP
.br
\fC#include 'Log\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
contains a program to test partially the Log class 


.PP
\fBAuthor:\fP
.RS 4
Samuel Andrew Wisner, awisner94@gmail.com 
.RE
.PP

.PP
Definition in file \fBlog_test\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main ()"
This program partially tests the Log class\&. 
.PP
Definition at line 18 of file log_test\&.cpp\&.
.PP
.nf
18            {
19     Log log("logs", LogMode::Text);
20     log\&.Debug("yolo!");
21     log\&.Variable("mymom","toldme");
22 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for ChipChipArray from the source code\&.
