.TH "src/main.cpp" 3 "Tue Mar 8 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <cstdlib>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <map>\fP
.br
\fC#include 'Servo_Position_Shell\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"
This program moves a specified servo to a specified position\&. It doubles as a test program for the functional servo interface (i\&.e\&., \fBServo_Position_Shell\&.cpp\fP)\&. 
.PP
Definition at line 23 of file main\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
