.TH "makefile" 3 "Fri Apr 22 2016" "ChipChipArray" \" -*- nroff -*-
.ad l
.nh
.SH NAME
makefile \- 
.PP
Project makefile containing recipes for compiling the actual application, test applications, and generating documentation\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Project makefile containing recipes for compiling the actual application, test applications, and generating documentation\&. 


.PP
\fBAuthor:\fP
.RS 4
Samuel Andrew Wisner, awisner94@gmail.com 
.RE
.PP

.PP
Definition in file \fBmakefile\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ChipChipArray from the source code\&.
