.TH "src/net_qr_test.cpp" 3 "Sat Mar 5 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/net_qr_test.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <opencv2/highgui/highgui\&.hpp>\fP
.br
\fC#include <opencv2/imgproc/imgproc\&.hpp>\fP
.br
\fC#include <zbar\&.h>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include 'PiCamera\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (intargc, char *argv[])"
This is a (modified) test program written by Michael Young (https://github.com/ayoungprogrammer/WebcamCodeScanner)\&. It was modified to work with the Raspicam\&. 
.PP
Definition at line 24 of file net_qr_test\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
