.TH "src/old_cv_test.cpp" 3 "Sun Feb 28 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/old_cv_test.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <core/core\&.hpp>\fP
.br
\fC#include <highgui/highgui\&.hpp>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include 'raspicam_cv\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"
This program was used to test the raspicam wrapper for OpenCV before implementing it in a more projet-friendly form as the PiCamera class\&. 
.PP
Definition at line 11 of file old_cv_test\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
