.TH "src/PiCamera.hpp" 3 "Sun Feb 28 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/PiCamera.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <opencv2/core/core\&.hpp>\fP
.br
\fC#include <opencv2/highgui/highgui\&.hpp>\fP
.br
\fC#include <raspicam/raspicam_cv\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBChipChipArray::PiCamera\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBChipChipArray\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
