.TH "src/ScanQR.hpp" 3 "Tue Mar 8 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ScanQR.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <opencv2/highgui/highgui\&.hpp>\fP
.br
\fC#include <opencv2/imgproc/imgproc\&.hpp>\fP
.br
\fC#include <zbar\&.h>\fP
.br
\fC#include 'definitions\&.hpp'\fP
.br
\fC#include 'Log\&.hpp'\fP
.br
\fC#include 'PiCamera\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBChipChipArray\fP"
.br
.RI "\fIcontains \fBBlock\fP class \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBColor\fP \fBChipChipArray::ScanQR\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBuint8\fP \fBChipChipArray::qrInvokeCount\fP = 0"
.br
.ti -1c
.RI "Log \fBChipChipArray::scanQrLog\fP ('logs/ScanQR', LogMode::Multi)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
