.TH "std" 3 "Sun Feb 28 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "string \fBto_string\fP (\fBBlockPosition\fP pos)"
.br
.ti -1c
.RI "string \fBto_string\fP (\fBColor\fP color)"
.br
.ti -1c
.RI "string \fBto_string\fP (\fBLogMode\fP mode)"
.br
.ti -1c
.RI "string \fBto_string\fP (\fBResult\fP res)"
.br
.ti -1c
.RI "string \fBto_string\fP (\fBSide\fP side)"
.br
.ti -1c
.RI "string \fBto_string\fP (\fBSize\fP size)"
.br
.ti -1c
.RI "string \fBto_string\fP (\fBZone\fP zone)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "string std::to_string (\fBBlockPosition\fPpos)"
Converts a BlockPosition to a string\&. 
.PP
Definition at line 80 of file definitions\&.hpp\&.
.SS "string std::to_string (\fBColor\fPcolor)"
Converts a Color to a string\&. 
.PP
Definition at line 88 of file definitions\&.hpp\&.
.SS "string std::to_string (\fBLogMode\fPmode)"
Converts a LogMode to a string\&. 
.PP
Definition at line 115 of file definitions\&.hpp\&.
.SS "string std::to_string (\fBResult\fPres)"
Converts a Result to a string\&. 
.PP
Definition at line 123 of file definitions\&.hpp\&.
.SS "string std::to_string (\fBSide\fPside)"
Converts a Side to a string\&. 
.PP
Definition at line 150 of file definitions\&.hpp\&.
.SS "string std::to_string (\fBSize\fPsize)"
Converts a Size to a string\&. 
.PP
Definition at line 158 of file definitions\&.hpp\&.
.SS "string std::to_string (\fBZone\fPzone)"
Converts a Zone to a string\&. 
.PP
Definition at line 166 of file definitions\&.hpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
