\hypertarget{makefile}{\section{makefile File Reference}
\label{makefile}\index{makefile@{makefile}}
}


Project makefile containing recipes for compiling the actual application, test applications, and generating documentation.  




\subsection{Detailed Description}
Project makefile containing recipes for compiling the actual application, test applications, and generating documentation. 

\begin{DoxyAuthor}{Author}
Samuel Andrew Wisner, \href{mailto:awisner94@gmail.com}{\tt awisner94@gmail.\+com} 
\end{DoxyAuthor}


Definition in file \hyperlink{makefile_source}{makefile}.

