ChipChipArray::PiCamera
raspicam::RaspiCam_Cv ChipChipArray::PiCamera::cam
the Raspicam object provided by raspicam_cv.h
ChipChipArray::PiCamera::PiCamera()
Opens the camera and configures it for color images.
ChipChipArray::PiCamera::PiCamera(bool useColor)
Opens the camera. useColor Specifices whether camera should make color images. TRUE = color, FALSE = grayscale.
void ChipChipArray::PiCamera::Close()
Closes connection to camera.
Referenced by ChipChipArray::Grabber::Close.
cv::Mat ChipChipArray::PiCamera::Snap()
Makes picture.OpenCV Mat object (i.e., an image) from the camera
Referenced by ChipChipArray::main, main, ChipChipArray::Grabber::LocateBlock, ChipChipArray::ScanQR.