Adafruit_PWMServoDriver
uint8_t Adafruit_PWMServoDriver::_i2caddr
int Adafruit_PWMServoDriver::_i2cFD
Adafruit_PWMServoDriver::Adafruit_PWMServoDriver(uint8_t addr=0x41)
void Adafruit_PWMServoDriver::begin(void)
References reset.
Referenced by setup.
void Adafruit_PWMServoDriver::reset(void)
References PCA9685_MODE1.
Referenced by begin.
void Adafruit_PWMServoDriver::setPWMFreq(float freq)
References ENABLE_DEBUG_OUTPUT, uint8_t, PCA9685_MODE1, PCA9685_PRESCALE.
Referenced by setup.
void Adafruit_PWMServoDriver::setPWM(uint8_t num, uint16_t on, uint16_t off)
References LED0_ON_L, LED0_OFF_L.
Referenced by setPin, setServoPulse.
void Adafruit_PWMServoDriver::setPin(uint8_t num, uint16_t val, bool invert=false)
References uint16_t, setPWM.
uint8_t Adafruit_PWMServoDriver::read8(uint8_t addr)
void Adafruit_PWMServoDriver::write8(uint8_t addr, uint8_t d)