ChipChipArray::Log
const char ChipChipArray::Log::PATH_SEP
The path sepearator. Can be changed if code adapted for Windows.
std::string ChipChipArray::Log::dir
The log file directory, including the directory created with LogMode::Multi.
std::string ChipChipArray::Log::filename
The log file filename.
uint8 ChipChipArray::Log::imgCount
The number of images saved in the image directory. Used in naming the images in LogMode::Multi.
LogMode ChipChipArray::Log::mode
The LogMode.
std::ofstream ChipChipArray::Log::file
The logfile.
const uint8 ChipChipArray::Log::LEN
The (maximum) length of the filename character array.
ChipChipArray::Log::Log()
Initializes Log object but does not open log. Open() must be called.
ChipChipArray::Log::Log(auto dir, LogMode mode=LogMode::Text)
Initializes the Log.A new log file is created in dir if LogMode::Text is given. The file will have a name based on the current date and time. If LogMode::Multi is given, a new directory is created, and a log file with a name based on the current date and time is created inside it. dir the directory for the newly created logfile/folder mode the LogMode
References Open.
ChipChipArray::Log::~Log()
Destroys the Log and closes the logfile.
void ChipChipArray::Log::Debug(auto mesg)
Writes "DEBUG: " to the log file along with the message passed. Should be used for generic debugging information. If recording the value of a variable in the Log is desired, use the function Variable() instead. mesg the message to record in the logfile
Referenced by ChipChipArray::Grabber::LocateBlock, main.
void ChipChipArray::Log::Error(auto mesg)
Writes "ERROR: " to the log file. Should only be use when an exception is thrown. mesg the message to record in the log
Referenced by Image.
void ChipChipArray::Log::Image(cv::Mat image, auto filename)
Creates a bitmap image in the subdirectory created by the Log during initialization. Does nothing if LogMode::Text was passed in the constructor. image the image to save filename the filename for the saved image
References Error.
Referenced by ChipChipArray::Grabber::LocateBlock.
void ChipChipArray::Log::Open(auto dir, LogMode mode=LogMode::Text)
References Multi.
Referenced by Log.
void ChipChipArray::Log::Status(auto mesg)
Writes "STATUS: " to the log file. Should be used when recording the status or state of the program. It should not be used to record microalgorithmic changes. Use Verbose() for these instead. mesg the message to record in the logfile
Referenced by ChipChipArray::Grabber::Close, ChipChipArray::Grabber::LocateBlock.
void ChipChipArray::Log::Variable(auto name, auto value)
Writes "VARIABLE: " to the log file. Should be used whenever recording the value of a variable is desired. name the variable name to record value the variable value to record
Referenced by main.
void ChipChipArray::Log::Verbose(auto mesg)
Writes "VERBOSE: " to the log file. Should only be used for recording small, specific portions of code. To record a change in the more general state of the program, use Status() instead. mesg the message to record in the logfile
Referenced by ChipChipArray::Grabber::Grabber, ChipChipArray::Grabber::LocateBlock.
void ChipChipArray::Log::LogError(auto mesg, std::ofstream::failure f)
Prints an error message and exits the application. Used when errors occur within this class ONLY. mesg the error message to print f the failure object caught