std
string std::to_string(BlockPosition pos)
Converts a BlockPosition to a string.
References Front.
Referenced by main, ChipChipArray::Grabber::Grabber, ChipChipArray::Grabber::LocateBlock.
string std::to_string(Color color)
Converts a Color to a string.
References ENUM.
string std::to_string(LogMode mode)
Converts a LogMode to a string.
References Multi.
string std::to_string(Result res)
Converts a Result to a string.
References ENUM.
string std::to_string(Side side)
Converts a Side to a string.
References Left.
string std::to_string(Size size)
Converts a Size to a string.
References Long.
string std::to_string(Zone zone)
Converts a Zone to a string.