Servo_Position_Shell.cpp
SERVOMIN
SERVOMAX
Adafruit_PWMServoDriver pwm
uint8_t servo_num
void setup()
Desc: This function sets up the breakout board communication with I2C using Adafruits_PWMServoDriver.cpp and to set the frequency of the servos to 60Hz.
References Adafruit_PWMServoDriver::begin, Adafruit_PWMServoDriver::setPWMFreq.
Referenced by main.
void setServoPulse(uint8_t servo_num, double pulse)
Desc: This function sets which servo to use and what pulse to set that servos pwm to. n which servo on the breakout board am I calling. Starting with 0. pulse what is the pulse length (in micro seconds) the pwm of the servo is set to.
References uint16_t, Adafruit_PWMServoDriver::setPWM.
Referenced by setServoPosition.
void setServoPosition(Servo whichservo, int position)
Desc: This function sets which servo to use using whichservo and what position out of 180 degrees for each servo (with limits). whichservo which servo would you like to use on the board position what position do you want to set the servo selected at
References setServoPulse.
Referenced by main.